title: Art in Touch
email: info@art-in-touch.de
formspree_form_path: f/moqbddzj
description: >- # this means to ignore newlines
  Ihre Ansprechpartner für Medienstationen im Museumsumfeld.

markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

collections:
  portfolio:
    output: true
    sort_by: date
  blog:
    output: true
    sort_by: date

defaults:
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
  -
    scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"

exclude:
  - build
  - .idea
  - Readme.md
  - Gemfile
  - Gemfile.lock
